# This workflow will check the source code and make sure that it follows the Google Java Style Guide
# For more information see: https://google.github.io/styleguide/javaguide.html
# and https://github.com/marketplace/actions/run-java-checkstyle

name: Java code style check
on: [push, pull_request]
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run check on sourcecode
        uses: dbelyaev/action-checkstyle@v0.3.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: ./custom_google_checks.xml
          reporter: github-pr-check
          level: error
